AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

  ExpirationPeriod:
    settings-key: AssetsServiceExpirationPeriod

HistoryExportBuilderJob:
    Db:
      LogsConnString:
        settings-key: HistoryExportLogsConnString
        types:
          - AzureTableStorage
      
      DataConnString:
        settings-key: HistoryExportDataConnString
        types:
          - AzureTableStorage
    
    GeneratedFileTtl:
      settings-key: HistoryExportFileTtl

    Cqrs:
        RabbitConnString:
            settings-key: CqrsRabbitConnString
            types:
                - RabbitMq	

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

HistoryServiceClient:
    ServiceUrl:
        settings-key: HistoryServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    
    QueueName: slack-notifications
  
  ThrottlingLimitSeconds:
    settings-key: SlackNotificationsThrottlingLimit
