AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

  ExpirationPeriod:
    settings-key: AssetsServiceExpirationPeriod

HistoryExportBuilderJob:
    Db:
      LogsConnString:
        settings-key: LogsConnString
        types:
          - AzureTableStorage
      
      DataConnString:
        settings-key: DataConnString
        types:
          - AzureTableStorage
    
    GeneratedFileTtl:
      settings-key: HistoryExportFileTtl

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

OperationsHistoryServiceClient:
  ServiceUrl:
    settings-key: OperationsHistoryServiceUrl

SagasRabbitMq:
  RabbitConnectionString:
    settings-key: SagasRabbitMqConnStr
    types:
      - RabbitMq
  
  RetryDelay:
    settings-key: SagasRetryDelay
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    
    QueueName: slack-notifications
  
  ThrottlingLimitSeconds:
    settings-key: SlackNotificationsThrottlingLimit
